import Head from 'next/head'
import NavBar from "@/pages/components/Navbar/NavBar";
import Image from "next/image";

import articleBg from "../../../public/images/articles_bg.svg";
import Footer from "@/pages/components/Footer";
import {Poppins} from "next/font/google";
import localFont from "next/font/local";
import {useTranslation} from "next-i18next";

const englishFont = Poppins({subsets: ['latin'], weight: ["400", "500", "600", "700", "800", "900"]})

const arabicFont = localFont({src: '../fonts/AGCRegular.ttf'})

export default function Index() {
    const {t, i18n} = useTranslation();

    return (
        <div
            className={`bg-mintyGreen min-h-screen ${i18n.language === "en" ? englishFont.className : arabicFont.className}`}>
            <Head>
                <title>Blog Page</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={'w-full'}>
                <NavBar className={`absolute`}/>
                <Image className={`w-[100%] h-fit`} src={articleBg} alt={``} width={1720} height={730}/>
            </div>

            <main className="w-full bg-contain bg-repeat bg-center bg-[url('/images/home_bg.svg')] bg-opacity-55 px-28">

                <div className={`text-xl text-darkGray pt-20`}>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate dolorem laudantium qui
                    voluptatum? Adipisci esse eveniet ex fugiat, impedit iste laudantium libero nulla, placeat quisquam
                    quod rem, sunt unde voluptas.
                </div>
                <div className={`text-darkGray mt-2`}>
                    05-10-2023
                </div>
                <div className={`text-darkGray mt-20`}>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is simply
                    dummy Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is
                    simply dummy.
                    <br/>
                    <br/>
                    <br/>

                    Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is simply
                    dummy Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is
                    simply dummy.
                    <br/>
                    <br/>
                    <br/>

                    Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is simply
                    dummy Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is
                    simply dummy.Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum
                    is simply dummy Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem
                    Ipsum is simply dummy.
                    <br/>
                    <br/>
                    <br/>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is simply
                    dummy Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum is
                    simply dummy.Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum
                    is simply dummy Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem
                    Ipsum is simply dummy.Lorem Ipsum is simply dummy text of the printing and typesetting industry
                    Lorem Ipsum is simply dummy Lorem Ipsum is simply dummy text of the printing and typesetting
                    industry Lorem Ipsum is simply dummy.Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry Lorem Ipsum is simply dummy Lorem Ipsum is simply dummy text of the printing
                    and typesetting industry Lorem Ipsum is simply dummy. <br/>

                </div>
                <div className="flex justify-center mt-10">
                <div
                        className={`flex items-center bg-darkGreen text-white p-2.5 px-12
                      rounded-full text-lg font-normal hover:bg-white hover:text-darkGreen 
                      border-2 border-solid border-transparent 
                      dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                      hover:dark:border-light md:p-2 md:px-4 md:text-base xs:text-xs
                      `}
                        style={{cursor: "pointer"}}
                        onClick={() => {

                        }}
                    >
                        Next Article
                    </div>
                </div>
            </main>
            <br/>
            <br/>
            <br/>
            <br/>
            <Footer/>
        </div>
    )
}
