import Head from 'next/head'
import NavBar from "@/pages/components/Navbar/NavBar";
import Image from "next/image";

import articleBg from "../../../public/images/articles_bg.svg";
import singleArticle from "../../../public/images/singleArticleBg.svg";
import Footer from "@/pages/components/Footer";
import ArticleCard from "@/pages/components/Articles/ArticleCard";
import {Poppins} from "next/font/google";
import localFont from "next/font/local";
import {useTranslation} from "next-i18next";
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import {getAllArticles} from "@/components/services/articles";
import SplashScreen from "@/pages/components/splash-screen";

const englishFont = Poppins({subsets: ['latin'], weight: ["400", "500", "600", "700", "800", "900"]})

const arabicFont = localFont({src: '../fonts/AGCRegular.ttf'})

export default function Index() {
    const {t, i18n} = useTranslation();
    const router = useRouter();
    const [articles, setArticles] = useState([]);
    useEffect(() => {
        getAllArticles().then((response) => {
            console.log(response);
            setArticles(response.articles.results);
        }).then((error) => {
            console.log(error);
        });
    }, []);

    if(!articles) {
        return <SplashScreen />
    }

    return (
        <div className={`bg-mintyGreen min-h-screen ${i18n.language === "en" ? englishFont.className : arabicFont.className}`}>
            <Head>
                <title>Blog Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={'w-full'}>
                <NavBar className={`absolute`}/>
                <Image className={`w-[100%] h-fit`} src={articleBg} alt={``} width={1720} height={730} />
            </div>

            <main className="w-full bg-contain bg-repeat bg-center bg-[url('/images/home_bg.svg')] bg-opacity-55">
                <div className={`w-full px-32 mt-20 mb-20 text-center`}>
                    <div className={`font-bold text-xl`}>
                        WEEKLY ARTICLES WITH INSIGHT INTO THE WEEKEND MESSAGE
                    </div>
                    <div className={`text-darkGreen text-xl font-light mt-10 px-40`}>
                        Our blog takes the message from the weekend and lays out next right steps,
                        so you can hear a message and do a message in practical ways.
                    </div>
                </div>

                <section className="w-full px-28 grid grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-x-1 gap-y-16">
                    {articles.map((article, index) => (
                        <ArticleCard key={index} image={singleArticle} text={article.body} title={article.title} date={article.updated_at} onClick={()=>{
                            router.push(`/articles/${index}`);
                        }} />
                    ))}
                </section>

                <div className="flex justify-center mt-10">
                    <div
                        className={`flex items-center bg-darkGreen text-white p-2.5 px-12
                      rounded-full text-lg font-normal hover:bg-white hover:text-darkGreen 
                      border-2 border-solid border-transparent 
                      dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                      hover:dark:border-light md:p-2 md:px-4 md:text-base xs:text-xs
                      `}
                        style={{cursor: "pointer"}}
                        onClick={() => {

                        }}
                    >
                        Load More
                    </div>
                </div>
            </main>
            <br/>
            <br/>
            <br/>
            <br/>
            <Footer/>
        </div>
    )
}
