import Footer from "@/components/Footer";
import Navebar from "@/components/Navbar";
import polygon2 from "../../public/images/svgs/Polygon 2.svg";
import "@/styles/globals.css";
import { AnimatePresence } from "framer-motion";

import Head from "next/head";
import { useRouter } from "next/router";
import { Poppins } from "next/font/google";
import Image from "next/image";
const poppins = Poppins({
  subsets: ["latin"],
  weight: "100",
  variable: "--font-mont",
});
export default function App({ Component, pageProps }) {
  const router = useRouter();
  const scrollToTarget = (elementId) => {
    // Get the position of the target element and scroll to it
    const targetElement = document.querySelector(`#${elementId}`);
    if (targetElement) {
      targetElement.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <>
      <Head>
        <title>Sahm Nakheel</title>
        <meta name="description" content="Generated by Sahm Nakheel" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`flex flex-col ${poppins.variable} font-mont bg-light dark:bg-dark w-full min-h-screen `}
      >
        <div className="absolute left-[60%] top-[0%] translate-x-[-0%] sm:top-0 z-0 sm:hidden">
          <Image src={polygon2} alt="" className="w-full h-auto" />
        </div>

        <Navebar scrollToTarget={scrollToTarget} />

        <AnimatePresence mode="wait">
          <Component key={router.asPath} {...pageProps} />
        </AnimatePresence>
        <Footer />
      </main>
    </>
  );
}
